spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    open-in-view: false
    properties:
      hibernate.search.backend:
        lucene_version: 'LATEST'
        directory.root: './temp/lucene/indices'
    database-platform: org.hibernate.dialect.MySQL5Dialect
admitad:
  access-grant-type: ${GRANT_ACCESS}
  refresh-grant-type: ${GRANT_REFRESH}
  client-id: ${CLIENT_ID}
  scope: ${SCOPE}
  authorization-token: ${AUTH_TOKEN}
  limit: 3
  schedule-update-shops: '0 * * ? * *'
  schedule-update-products: '0 * * ? * *'
